# below are all optional configurations. if there is a value present, that is
# the default value. to override a value, change it and uncomment that line of
# the config.

# server:
#   addr: 127.0.0.1:8080
#   tls-cert:
#   tls-key:
#   tls-ca:
#   username_header: username
# datasource:
#   url: localhost
#   database: etre
#   timeout: 5
#   tls-cert:
#   tls-key:
#   tls-ca:
#   username:
#   source:
#   mechanism:
# entity:
#   types:
#     - node
# cdc:
#   collection: cdc
#   fallbackFile:
#   write_retry_count: 3
#   write_retry_wait: 50 # milliseconds
# delay:
#   collection: delay
#   static_delay_ms: -1 # milliseconds
# feed:
#   streamer_buffer_size: 100
#   poll_interval: 2000
